### ISSUE TITLE
Make available on NPM

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic-bower#18]
Hi,

it would be great if this would also be available via NPM, we don't need bower at all and would like to have Ionic in NPM so we can use our private npm-cache.

Best,
Andreas

**Comment by ichabodcole** [comment]
+1 just call it ionic-client

**Comment by ptarjan** [comment]
+1

**Comment by dhoko** [comment]
+1

**Comment by BigstickCarpet** [comment]
+:100:  Bower's great and all, but there are some scenarios where only npm will do

**Comment by adamdbradley** [comment]
Just created this, please let us know how it goes:
https://www.npmjs.com/package/ionic-sdk

**Comment by BigstickCarpet** [comment]
Awesome! That is immediately useful for several of my projects.  Thanks!
