### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by 7freaks-otte** [driftyco/ionic-bower#22]
I just saw you updated to v1.1.1. In order to user bower to update ionic, can you please tag the current version with v1.1.1.

Just had to check out #master which ist OK at the moment but if I do a bower update in my project in the future I want to stay on v1.1.1 and not get a nightly.

Thanks

**Comment by perrygovier** [comment]
Done, sorry for the trouble

**Comment by 7freaks-otte** [comment]
thanks a lot :-)
