### ISSUE TITLE
v1.3.0 contains angular 1.4.3 and not angular 1.5.3

### ISSUE THREAD

**Issue by mvandenbrink** [driftyco/ionic-bower#30]
I had to use a nightly build in my Ionic project after an ionic upgrade to get the correct Angular 1.5.3. version.

**Comment by moisesnarvaez** [comment]
+1

**Comment by horozco** [comment]
+1

**Comment by CramericaIndustries** [comment]
+1

**Comment by jimior2** [comment]
+1, just confuse about this, why ionic's angular version different than ionic-bower's angular version?

**Comment by dtslvr** [comment]
+1

**Comment by hungdoan2** [comment]
@mvandenbrink Which version did you download ?  
for this build of 1.3.0 https://github.com/driftyco/ionic-bower/commit/e196c131dacd9132d7187dd92e03a9328e8cab90, They use angular 1.5.3, and there is no different between this build & the build from main repository.

**Comment by mvandenbrink** [comment]
@hungdoan2 I changed my dependency to "driftyco/ionic-bower#v1.3.0-nightly-3116". The release 1.3.0 https://github.com/driftyco/ionic-bower/commit/e196c131dacd9132d7187dd92e03a9328e8cab90 contains this in its bower.json file:

```
  "dependencies": {
    "angular": "1.4.3",
    "angular-animate": "1.4.3",
    "angular-sanitize": "1.4.3",
    "angular-ui-router": "0.2.13"
  }
```

Since build 1.3.0 https://github.com/driftyco/ionic-bower/commit/27e9f81bb84ef64b2cf2d2fb6719568a9a25156f is the correct angular 1.5.3 used as dependency.

**Comment by hungdoan2** [comment]
@mvandenbrink I got it. Maybe they forgot to update the dependency information in the build. But in the distribution file they still use Angular 1.5.3.

@jimior2 they are not different. The distribution files are the same. But the metadata file (bower.json) was wrong(I think they forgot to update them :) )

**Comment by jimior2** [comment]
@hungdoan2 got it. thanks for your reply.

**Comment by mvandenbrink** [comment]
Ionic 1.3.1 contains the right Angular version
