### ISSUE TITLE
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/driftyco/ionic-bower.git",

### ISSUE THREAD

**Issue by movilujo** [driftyco/ionic-bower#33]
bower ionic#1.3.1              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/driftyco/ionic-bower.git",
 exit code of #128 fatal: read error: Invalid argument

**Comment by movilujo** [comment]
I've put this issue by mistake. I'm sorry

**Comment by frontexpert** [comment]
I've got this error while installing angular-local-storage
bower ionic#1.3.2     ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/driftyco/ionic-bower.git", exit code of #128 fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.
