### ISSUE TITLE
Module 'starter' is not available

### ISSUE THREAD

**Issue by thatjuan** [driftyco/ionic-bower#5]
I've added ionic-bower@v1.0.0-beta.9-nightly-270 using bower to an existing Cordova 3.5.0 app. 

I also included lib/ionic/js/ionic.bundle.js in my index.html

I get the following error when I start my app:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:nomod] Module 'starter' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specif...<omitted>...0) 
```

I missing any other dependencies?

**Comment by prashanthmotifworks** [comment]
Did you removed the tag to resolve this issue thatjuan

**Comment by Floryzzz** [comment]
@thatjuan thx fam
